jobs:
  e2e-tests:
    working_directory: ~/project
    docker:
      - image: 'cypress/base:14.18.1'
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: build
          command: npm run cypress:build
      - run:
          name: start-server
          command: npm run cypress:start
          background: true
      - run:
          name: e2e-tests
          command: npm run e2e-test
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots


workflows:
  code-checks:
    jobs:
      - e2e-tests

